/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PagarKun
 */
public class Form_MenuUtamaUser extends javax.swing.JFrame {
    koneksi kon = new koneksi();
    Connection connec;
    PreparedStatement psmnt = null;
    ImageIcon format;
    ResultSet rs;

    public String kode;
    public String Level;
    public String NamaUser;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_MenuUtamaUser.class.getName());

    /**
     * Creates new form Form_MenuUtamaUser
     */
    public Form_MenuUtamaUser() {
        initComponents();

        setTanggal();
        setJam();

        kon.setkoneksi();
    }
    
    public String getKodeUser() {
        return kode;
    }

    public String getNamaUser() {
        return NamaUser;
    }

    public String getLevel() {
        return Level;
    }
    
     public void setTanggal() {

        java.util.Date skrg = new java.util.Date();

        java.text.SimpleDateFormat kal =
                new java.text.SimpleDateFormat("dd MMMM yyyy");

        date2.setText(kal.format(skrg));
    }
     
     public void setJam() {

    ActionListener taskPerformer = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent evt) {

            java.util.Date now = new java.util.Date();

            int jam = now.getHours();
            int menit = now.getMinutes();
            int detik = now.getSeconds();

            clock.setText(String.format("%02d:%02d:%02d", jam, menit, detik));
        }
    };

    new Timer(1000, taskPerformer).start();

}
     
     
     private void getfoto() {

        // isi getfoto()

    }
     
     
     
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Inama = new javax.swing.JLabel();
        Ikode = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        Ilevel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnlogout = new javax.swing.JMenuItem();
        mngantipassword = new javax.swing.JMenuItem();
        mnkeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jbarang_masuk = new javax.swing.JMenuItem();
        jbarang_keluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnlapbarang = new javax.swing.JMenuItem();
        mnlapbrgmsk = new javax.swing.JMenuItem();
        mnlapbrgklr = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jdata_barang = new javax.swing.JMenuItem();
        jstok_min = new javax.swing.JMenuItem();

        jPanel4.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("APLIKASI INVENTORY");

        Inama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Inama.setText("jLabel3");

        Ikode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ikode.setText("jLabel2");

        date2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date2.setText("jLabel5");

        clock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clock.setText("jLabel4");

        Ilevel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Ilevel.setText("jLabel1");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ikode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inama, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ilevel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clock)
                                    .addComponent(date2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inama)
                    .addComponent(date2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clock)
                    .addComponent(Ikode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ilevel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jMenu1.setText("Keluar");

        mnlogout.setText("LogOut");
        mnlogout.addActionListener(this::mnlogoutActionPerformed);
        jMenu1.add(mnlogout);

        mngantipassword.setText("Ganti Password");
        jMenu1.add(mngantipassword);

        mnkeluar.setText("Keluar");
        mnkeluar.addActionListener(this::mnkeluarActionPerformed);
        jMenu1.add(mnkeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        jbarang_masuk.setText("Barang Masuk");
        jbarang_masuk.addActionListener(this::jbarang_masukActionPerformed);
        jMenu2.add(jbarang_masuk);

        jbarang_keluar.setText("Barang Keluar");
        jbarang_keluar.addActionListener(this::jbarang_keluarActionPerformed);
        jMenu2.add(jbarang_keluar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        mnlapbarang.setText("Laporan Barang");
        mnlapbarang.addActionListener(this::mnlapbarangActionPerformed);
        jMenu3.add(mnlapbarang);

        mnlapbrgmsk.setText("Laporan Barang Masuk");
        mnlapbrgmsk.addActionListener(this::mnlapbrgmskActionPerformed);
        jMenu3.add(mnlapbrgmsk);

        mnlapbrgklr.setText("Laporan Barang Keluar");
        mnlapbrgklr.addActionListener(this::mnlapbrgklrActionPerformed);
        jMenu3.add(mnlapbrgklr);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Data");

        jdata_barang.setText("Data Barang");
        jdata_barang.addActionListener(this::jdata_barangActionPerformed);
        jMenu4.add(jdata_barang);

        jstok_min.setText("Stok Barang Minimal");
        jstok_min.addActionListener(this::jstok_minActionPerformed);
        jMenu4.add(jstok_min);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbarang_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarang_masukActionPerformed
        Form_Penerimaan_Barang  
        BM = new Form_Penerimaan_Barang();         
        BM.setLocationRelativeTo(null);         
        BM.setVisible(true);         
        BM.kode=Ikode.getText(); 
    }//GEN-LAST:event_jbarang_masukActionPerformed

    private void jbarang_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarang_keluarActionPerformed
         Form_Pengeluaran_Barang  
         BK = new Form_Pengeluaran_Barang();         
         BK.setLocationRelativeTo(null);         
         BK.setVisible(true);         
         BK.kode=Ikode.getText(); 
    }//GEN-LAST:event_jbarang_keluarActionPerformed

    private void mnlapbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlapbarangActionPerformed
         try{             
             String path="src/gudang/Laporan_Barang.jasper";             
             HashMap parameter = new HashMap();             
             JasperPrint print = JasperFillManager.fillReport(path,parameter,kon.setkoneksi());             
             JasperViewer.viewReport(print, false);         }         
         catch(Exception e) {             
             JOptionPane.showMessageDialog(null, e);         } 
    }//GEN-LAST:event_mnlapbarangActionPerformed

    private void mnlapbrgklrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlapbrgklrActionPerformed
        Form_Laporan_PengeluaranPeriode Laporan_Klr = new Form_Laporan_PengeluaranPeriode();        
        Laporan_Klr.setLocationRelativeTo(null);        
        Laporan_Klr.setVisible(true); 
    }//GEN-LAST:event_mnlapbrgklrActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Inama.setText(NamaUser);         
       Ikode.setText(kode);        
       Ilevel.setText(Level);         
       getfoto(); 
    }//GEN-LAST:event_formWindowActivated

    private void mnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlogoutActionPerformed
         this.dispose();         
         Form_Login login = new Form_Login();
         login.setLocationRelativeTo(null);         
         login.setVisible(true); 
    }//GEN-LAST:event_mnlogoutActionPerformed

    private void mnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkeluarActionPerformed
         System.exit(0); 
    }//GEN-LAST:event_mnkeluarActionPerformed

    private void jdata_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdata_barangActionPerformed
        Form_Data_Barang DB = new Form_Data_Barang();         
        DB.setLocationRelativeTo(null);          
        DB.setVisible(true);
    }//GEN-LAST:event_jdata_barangActionPerformed

    private void jstok_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstok_minActionPerformed
         Form_Stok_Barang_Minimal  
         DSMB = new Form_Stok_Barang_Minimal();
         DSMB.setLocationRelativeTo(null);         
         DSMB.setVisible(true); 
    }//GEN-LAST:event_jstok_minActionPerformed

    private void mnlapbrgmskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlapbrgmskActionPerformed
           Form_Laporan_PenerimaanPeriode Laporan_Msk = new Form_Laporan_PenerimaanPeriode();
           Laporan_Msk.setLocationRelativeTo(null);        
           Laporan_Msk.setVisible(true);      
    }//GEN-LAST:event_mnlapbrgmskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_MenuUtamaUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ikode;
    private javax.swing.JLabel Ilevel;
    private javax.swing.JLabel Inama;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JMenuItem jbarang_keluar;
    private javax.swing.JMenuItem jbarang_masuk;
    private javax.swing.JMenuItem jdata_barang;
    private javax.swing.JMenuItem jstok_min;
    private javax.swing.JMenuItem mngantipassword;
    private javax.swing.JMenuItem mnkeluar;
    private javax.swing.JMenuItem mnlapbarang;
    private javax.swing.JMenuItem mnlapbrgklr;
    private javax.swing.JMenuItem mnlapbrgmsk;
    private javax.swing.JMenuItem mnlogout;
    // End of variables declaration//GEN-END:variables
}
