/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;

/**
 *
 * @author PagarKun
 */
public class Form_Login extends javax.swing.JFrame { 
    koneksi kon = new koneksi(); 
    public Form_MenuUtamaAdmin menu = null; 

    /** 
     * Creates new form Form_Login 
     */ 
    public Form_Login() { 
        initComponents(); 
        kon.setkoneksi(); 
        tlevel.setVisible(false); 
    } 

    void bersih() { 
        tnik_user.setText(""); 
        tpassword.setText(""); 
        tlevel.setText(""); 
    } 

    @Override
    public void setTitle(String title) { 
        super.setTitle("L O G I N");  
    } 
    
    
    // Method untuk mengubah visibilitas password
    private void togglePassword(JPasswordField field, JCheckBox chkBox) {
        if (chkBox.isSelected()) {
            // Tampilkan karakter asli (Password Terlihat)
            field.setEchoChar((char) 0);
        } else {
            // Sembunyikan karakter (Default Bulatan Password)
            field.setEchoChar('\u2022'); // atau '*' tergantung Look & Feel
        }
    }

   private void prosesLogin() { 
    try { 
        String nikUser = tnik_user.getText().trim();
        String passInput = String.valueOf(tpassword.getPassword()).trim();

        // Query memeriksa password dalam format Teks Biasa ATAU Hash MD5
        String sql = "SELECT * FROM tb_user WHERE id_user='" + nikUser + "' "
                   + "AND (password='" + passInput + "' OR password=MD5('" + passInput + "'))"; 

        kon.rs = kon.st.executeQuery(sql); 

        if (kon.rs.next()) { 
            String level = kon.rs.getString("level");

            if (level.equals("1")) { 
                Form_MenuUtamaAdmin menuAdmin = new Form_MenuUtamaAdmin(); 
                menuAdmin.setLocationRelativeTo(null); 
                menuAdmin.NamaUser = kon.rs.getString("nm_user"); 
                menuAdmin.kode = kon.rs.getString("id_user"); 
                menuAdmin.Level = level; 
                menuAdmin.setVisible(true); 
                this.dispose(); 
            } else if (level.equals("2")) { 
                Form_MenuUtamaUser menuUser = new Form_MenuUtamaUser(); 
                menuUser.setLocationRelativeTo(null); 
                menuUser.NamaUser = kon.rs.getString("nm_user"); 
                menuUser.kode = kon.rs.getString("id_user"); 
                menuUser.Level = level; 
                menuUser.setVisible(true); 
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(null, "Level User (" + level + ") tidak dikenali!");
            }
        } else { 
            JOptionPane.showMessageDialog(null, "KODE USER ATAU PASSWORD SALAH!"); 
            bersih(); 
            tnik_user.setEnabled(true); 
            tnik_user.requestFocus(); 
        } 
    } catch (SQLException e) { 
        JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage()); 
    } 
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tnik_user = new javax.swing.JTextField();
        tpassword = new javax.swing.JPasswordField();
        tlevel = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        bt_keluar = new javax.swing.JButton();
        chkShowPassword = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        tnik_user.addActionListener(this::tnik_userActionPerformed);

        tlevel.addActionListener(this::tlevelActionPerformed);

        bt_login.setText("Masuk");
        bt_login.addActionListener(this::bt_loginActionPerformed);

        bt_keluar.setText("Keluar");
        bt_keluar.addActionListener(this::bt_keluarActionPerformed);

        chkShowPassword.setText("Lihat");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);

        jLabel3.setText("Kode User");

        jLabel4.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tlevel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tnik_user)
                                    .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnik_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkShowPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 460, 250));

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 460, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlevelActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        prosesLogin();
    }//GEN-LAST:event_bt_loginActionPerformed

    private void tnik_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnik_userActionPerformed
        String nikuser = tnik_user.getText(); 

        try { 
            String sql = "Select *from tb_user where id_user='" + nikuser + "'"; 
            kon.rs = kon.st.executeQuery(sql); 

            if (kon.rs.next()) { 
                tlevel.setText(kon.rs.getString("level")); 
                tpassword.setEnabled(true); 
                tpassword.requestFocus(); 
                bt_login.setEnabled(true); 
                tnik_user.setEnabled(true); 
            } else { 
                JOptionPane.showMessageDialog(null, "kode user salah"); 
                bersih(); 
                tnik_user.setEnabled(true); 
                tnik_user.requestFocus(); 
            } 
        } catch (SQLException e) { 
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_tnik_userActionPerformed

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_keluarActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed
        togglePassword(tpassword, chkShowPassword);
    }//GEN-LAST:event_chkShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton bt_login;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tlevel;
    private javax.swing.JTextField tnik_user;
    private javax.swing.JPasswordField tpassword;
    // End of variables declaration//GEN-END:variables
}
