/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author PagarKun
 */
public class Form_Laporan_TransaksiPeriode extends javax.swing.JFrame { 
    koneksi kon = new koneksi(); 
    JasperReport jasperReport; 
    JasperDesign jasperDesign; 
    JasperPrint jasperPrint;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Laporan_TransaksiPeriode.class.getName());

    /**
     * Creates new form Form_Laporan_PengeluaranPeriode
     */
   public Form_Laporan_TransaksiPeriode() { 
    initComponents(); 
    kon.setkoneksi(); 
    
    // Inisialisasi Pilihan Bulan di ComboBox
    cmbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
        "January", "February", "March", "April", "May", "June", 
        "July", "August", "September", "October", "November", "December" 
    }));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dctglawal = new com.toedter.calendar.JDateChooser();
        dctglakhir = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btcetakperiode = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbbulan = new javax.swing.JComboBox<>();
        yctahun = new com.toedter.calendar.JYearChooser();
        btcetakbulan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Per Tanggal"));

        jLabel2.setText("Dari Tanggal");

        jLabel3.setText("Sampai Tanggal");

        btcetakperiode.setBackground(new java.awt.Color(204, 204, 204));
        btcetakperiode.setText("Cetak");
        btcetakperiode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btcetakperiode.addActionListener(this::btcetakperiodeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dctglawal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dctglakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btcetakperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dctglawal, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(dctglakhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btcetakperiode, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 450, 170));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Per Bulan"));

        cmbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btcetakbulan.setBackground(new java.awt.Color(204, 204, 204));
        btcetakbulan.setText("Cetak");
        btcetakbulan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btcetakbulan.addActionListener(this::btcetakbulanActionPerformed);

        jLabel4.setText("Bulan");

        jLabel5.setText("Tahun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yctahun, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btcetakbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btcetakbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbbulan, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(yctahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 450, 170));

        bt_keluar.setBackground(new java.awt.Color(204, 204, 204));
        bt_keluar.setText("Keluar");
        bt_keluar.addActionListener(this::bt_keluarActionPerformed);
        getContentPane().add(bt_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 393, 450, 40));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcetakperiodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakperiodeActionPerformed
        if (dctglawal.getDate() == null || dctglakhir.getDate() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih tanggal awal dan tanggal akhir terlebih dahulu!");
        return;
    }

    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    String tgl1 = formatter.format(dctglawal.getDate()); 
    String tgl2 = formatter.format(dctglakhir.getDate()); 

    try { 
        // Path fisik Maven yang benar
        String NamaFile = "src/main/java/gudang/Laporan_Transaksi_Pertanggal.jasper"; 
        
        HashMap<String, Object> parameter = new HashMap<>(); 
        parameter.put("tgl_awal", tgl1); 
        parameter.put("tgl_akhir", tgl2); 

        JasperPrint print = JasperFillManager.fillReport(NamaFile, parameter, kon.setkoneksi()); 
        JasperViewer.viewReport(print, false); 
    } catch (Exception ex) { 
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Membuka Laporan Transaksi Pertanggal: " + ex.getMessage()); 
    }
    }//GEN-LAST:event_btcetakperiodeActionPerformed

    private void btcetakbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcetakbulanActionPerformed
        try { 
        // Path fisik Maven yang benar
        String NamaFile = "src/main/java/gudang/Laporan_Transaksi_Perbulan.jasper"; 

        HashMap<String, Object> parameter = new HashMap<>(); 
        
        // Mengubah index bulan (0-11) menjadi angka bulan (1-12)
        int bulanAngka = cmbbulan.getSelectedIndex() + 1;
        
        parameter.put("bulan_angka", bulanAngka); 
        parameter.put("tahun", yctahun.getYear()); 

        JasperPrint print = JasperFillManager.fillReport(NamaFile, parameter, kon.setkoneksi()); 
        JasperViewer.viewReport(print, false); 
    } catch (Exception ex) { 
        ex.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Membuka Laporan Transaksi Perbulan: " + ex.getMessage()); 
    }
    }//GEN-LAST:event_btcetakbulanActionPerformed

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed

        dispose();
    }//GEN-LAST:event_bt_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Laporan_TransaksiPeriode().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton btcetakbulan;
    private javax.swing.JButton btcetakperiode;
    private javax.swing.JComboBox<String> cmbbulan;
    private com.toedter.calendar.JDateChooser dctglakhir;
    private com.toedter.calendar.JDateChooser dctglawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JYearChooser yctahun;
    // End of variables declaration//GEN-END:variables
}
