/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hype
 */
public class Form_Data_Barang_Keluar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Data_Barang_Keluar.class.getName());

    // Inisialisasi variabel koneksi dan data tabel
    koneksi kon = new koneksi();
    
    // Menggunakan Object sementara jika Form_Pengeluaran_Barang belum dibuat
    public Object barang1 = null; 
    
    private Object[][] databarang = null;
    private String[] label = {"KODE BARANG", "NAMA KATEGORI", "NAMA BARANG", "STOK", "MIN.STOK"};

    /**
     * Creates new form Form_Data_Barang_Keluar
     */
    public Form_Data_Barang_Keluar() {
        initComponents();
        kon.setkoneksi();
        BacaTabelBarang();
    }

    private void BacaTabelBarang() {
        try {
            String sql = "Select *From tb_barang order by kd_brg";
            kon.rs = kon.st.executeQuery(sql);
            ResultSetMetaData m = kon.rs.getMetaData();
            int kolom = m.getColumnCount();
            int baris = 0;
            while (kon.rs.next()) {
                baris = kon.rs.getRow();
            }
            databarang = new Object[baris][kolom];
            int x = 0;
            kon.rs.beforeFirst();
            while (kon.rs.next()) {
                databarang[x][0] = kon.rs.getString("kd_brg");
                databarang[x][1] = kon.rs.getString("nm_kategori");
                databarang[x][2] = kon.rs.getString("nm_brg");
                databarang[x][3] = kon.rs.getString("stok");
                databarang[x][4] = kon.rs.getString("min_stok");
                x++;
            }
            tbl_barang.setModel(new DefaultTableModel(databarang, label));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void CariTabelBarang() {
        try {
            String sql = "select *from tb_barang where kd_brg like '%" + tcari.getText() + "%'"
                    + "or nm_kategori like '%" + tcari.getText() + "%'"
                    + "or nm_brg like '%" + tcari.getText() + "%'";
            kon.rs = kon.st.executeQuery(sql);
            ResultSetMetaData m = kon.rs.getMetaData();
            int kolom = m.getColumnCount();
            int baris = 0;
            while (kon.rs.next()) {
                baris = kon.rs.getRow();
            }
            databarang = new Object[baris][kolom];
            int x = 0;
            kon.rs.beforeFirst();
            while (kon.rs.next()) {
                databarang[x][0] = kon.rs.getString("kd_brg");
                databarang[x][1] = kon.rs.getString("nm_kategori");
                databarang[x][2] = kon.rs.getString("nm_brg");
                databarang[x][3] = kon.rs.getString("stok");
                databarang[x][4] = kon.rs.getString("min_stok");
                x++;
            }
            tbl_barang.setModel(new DefaultTableModel(databarang, label));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tcari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_barang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 480, 260));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        tcari.setBackground(new java.awt.Color(0, 51, 255));
        tcari.setForeground(new java.awt.Color(255, 255, 255));
        tcari.setText("Cari barang");
        tcari.setSelectedTextColor(new java.awt.Color(0, 51, 204));
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tcari, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gudang/lux.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void tcariKeyTyped(java.awt.event.KeyEvent evt) {                               
        CariTabelBarang();
    }                              

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {                                        
        int tabelbarang = tbl_barang.getSelectedRow();
        if (barang1 != null) {
            try {
                barang1.getClass().getField("KdBrg").set(barang1, tbl_barang.getValueAt(tabelbarang, 0).toString());
                barang1.getClass().getField("NmKategori").set(barang1, tbl_barang.getValueAt(tabelbarang, 1).toString());
                barang1.getClass().getField("NmBrg").set(barang1, tbl_barang.getValueAt(tabelbarang, 2).toString());
            } catch (Exception e) {
                // Ignore jika field belum diset
            }
        }
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Data_Barang_Keluar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
