/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gudang;
import com.mycompany.gudang.koneksi;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Stok_Barang_MinimalPM extends javax.swing.JDialog {
    koneksi kon = new koneksi(); 
    // PERBAIKAN 1: Ganti tipe form induk ke Form_Transaksi_Inventory
    public Object barang1 = null; // Bisa menerima form induk apa saja    
    private Object [][] databarang = null;
    private String[] label = {"KODE BARANG","NAMA KATEGORI","NAMA BARANG","STOK","MIN.STOK"};

    public Form_Stok_Barang_MinimalPM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kon.setkoneksi();        
        BacaTabelBarang();
    }

    private void BacaTabelBarang() {     
    try {          
        // Tampilkan semua barang agar barang baru tetap muncul
        String sql = "SELECT * FROM tb_barang ORDER BY kd_brg";      
        kon.rs = kon.st.executeQuery(sql);       
        ResultSetMetaData m = kon.rs.getMetaData();     
        int kolom = m.getColumnCount();        
        int baris = 0;         
        
        while (kon.rs.next()) {           
            baris = kon.rs.getRow();  
        }          
        
        databarang = new Object[baris][kolom];   
        int x = 0;     
        kon.rs.beforeFirst();     
        
        while(kon.rs.next()) {           
            databarang[x][0] = kon.rs.getString("kd_brg");     
            databarang[x][1] = kon.rs.getString("nm_kategori");   
            databarang[x][2] = kon.rs.getString("nm_brg");     
            databarang[x][3] = kon.rs.getString("stok");       
            databarang[x][4] = kon.rs.getString("min_stok");  
            x++;     
        }      
        tbl_barang.setModel(new DefaultTableModel(databarang, label));  
    } catch(SQLException e) {    
        JOptionPane.showMessageDialog(null, "Gagal memuat tabel barang: " + e.getMessage());     
    }  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_barang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 280));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
       int tabelbarang = tbl_barang.getSelectedRow();   
    
    // Pastikan baris tabel dipilih dan variabel barang1 tidak null
    if (tabelbarang != -1 && barang1 != null) {
        // 1. Ambil data dari baris tabel yang diklik
        String kd = tbl_barang.getValueAt(tabelbarang, 0).toString();
        String kat = tbl_barang.getValueAt(tabelbarang, 1).toString();
        String nm = tbl_barang.getValueAt(tabelbarang, 2).toString();

        // 2. Cek form mana yang sedang memanggil dialog ini (Casting)
        if (barang1 instanceof Form_Penerimaan_Barang) {
            Form_Penerimaan_Barang f = (Form_Penerimaan_Barang) barang1;
            f.KdBrg = kd;
            f.NmKategori = kat;
            f.NmBrg = nm;
        } 
        else if (barang1 instanceof Form_Transaksi_Inventory) {
            Form_Transaksi_Inventory f = (Form_Transaksi_Inventory) barang1;
            f.KdBrg = kd;
            f.NmKategori = kat;
            f.NmBrg = nm;
        }
        // ---> TAMBAHKAN BLOK KODE INI <---
        else if (barang1 instanceof Form_Pengeluaran_Barang) {
            Form_Pengeluaran_Barang f = (Form_Pengeluaran_Barang) barang1;
            f.KdBrg = kd;
            f.NmKategori = kat;
            f.NmBrg = nm;
        }

        // 3. Tutup JDialog
        this.dispose(); 
    }
    }//GEN-LAST:event_tbl_barangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Stok_Barang_MinimalPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Stok_Barang_MinimalPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Stok_Barang_MinimalPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Stok_Barang_MinimalPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Stok_Barang_MinimalPM dialog = new Form_Stok_Barang_MinimalPM(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_barang;
    // End of variables declaration//GEN-END:variables
}
