/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author PagarKun
 */
public class Form_MenuUtamaAdmin extends javax.swing.JFrame {
    
    koneksi kon = new koneksi();
    Connection connec;
    PreparedStatement psmnt = null;
    ImageIcon format;
    ResultSet rs;

    public String kode;
    public String Level;
    public String NamaUser;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_MenuUtamaAdmin.class.getName());

    /**
     * Creates new form Form_MenuUtamaAdmin
     */
   public Form_MenuUtamaAdmin() {
    initComponents();

    setTanggal();
    setJam();

    kon.setkoneksi();
    }
   
   public String getKodeUser() {
    return kode;
}

   public String getNamaUser() {
    return NamaUser;
}

   public String getLevel() {
    return Level;
}
   public void setTanggal() {

    java.util.Date skrg = new java.util.Date();

    java.text.SimpleDateFormat kal =
            new java.text.SimpleDateFormat("dd MMMM yyyy");

    date.setText(kal.format(skrg));

}
   public void setJam() {

    ActionListener taskPerformer = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent evt) {

            java.util.Date now = new java.util.Date();

            int jam = now.getHours();
            int menit = now.getMinutes();
            int detik = now.getSeconds();

            clock.setText(String.format("%02d:%02d:%02d", jam, menit, detik));
        }
    };

    new Timer(1000, taskPerformer).start();

}
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Inama = new javax.swing.JLabel();
        Ikode = new javax.swing.JLabel();
        Ilevel = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnlogout = new javax.swing.JMenuItem();
        mngantipassword = new javax.swing.JMenuItem();
        mnkeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnbarang = new javax.swing.JMenuItem();
        mnuser = new javax.swing.JMenuItem();
        mnkategori = new javax.swing.JMenuItem();
        nmTranksaksi = new javax.swing.JMenu();
        jbarang_masuk = new javax.swing.JMenuItem();
        jbarang_keluar = new javax.swing.JMenuItem();
        jOrderInventory = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnlapbrg = new javax.swing.JMenuItem();
        mnlapuser = new javax.swing.JMenuItem();
        mnlaporder = new javax.swing.JMenuItem();
        mnLapBrgMsk = new javax.swing.JMenuItem();
        mnLapBrgKlr = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jdata_barang = new javax.swing.JMenuItem();
        jstok_min = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI INVENTORY");
        jLabel1.setRequestFocusEnabled(false);

        Inama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Inama.setText("RIZQI PUTRA");

        Ikode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ikode.setText("Kode");

        Ilevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ilevel.setText("Akses Level");

        date.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        date.setText("Date");

        clock.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        clock.setText("Clock");

        foto2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        foto2.setText("Foto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APLIKASI INVENTORY");
        jLabel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Ikode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Inama, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Ilevel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inama)
                    .addComponent(date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clock)
                    .addComponent(Ikode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ilevel)
                    .addComponent(foto2))
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 520, 270));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));

        jMenu1.setText("Keluar");

        mnlogout.setText("LogOut");
        mnlogout.addActionListener(this::mnlogoutActionPerformed);
        jMenu1.add(mnlogout);

        mngantipassword.setText("Ganti Password");
        mngantipassword.addActionListener(this::mngantipasswordActionPerformed);
        jMenu1.add(mngantipassword);

        mnkeluar.setText("Keluar");
        mnkeluar.addActionListener(this::mnkeluarActionPerformed);
        jMenu1.add(mnkeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");

        mnbarang.setText("Barang");
        mnbarang.addActionListener(this::mnbarangActionPerformed);
        jMenu2.add(mnbarang);

        mnuser.setText("User");
        mnuser.addActionListener(this::mnuserActionPerformed);
        jMenu2.add(mnuser);

        mnkategori.setText("Kategori");
        mnkategori.addActionListener(this::mnkategoriActionPerformed);
        jMenu2.add(mnkategori);

        jMenuBar1.add(jMenu2);

        nmTranksaksi.setText("Tranksaksi");

        jbarang_masuk.setText("Barang Masuk");
        jbarang_masuk.addActionListener(this::jbarang_masukActionPerformed);
        nmTranksaksi.add(jbarang_masuk);

        jbarang_keluar.setText("Barang Keluar");
        jbarang_keluar.addActionListener(this::jbarang_keluarActionPerformed);
        nmTranksaksi.add(jbarang_keluar);

        jOrderInventory.setText("Order Inventory");
        jOrderInventory.addActionListener(this::jOrderInventoryActionPerformed);
        nmTranksaksi.add(jOrderInventory);

        jMenuBar1.add(nmTranksaksi);

        jMenu3.setText("Laporan");

        mnlapbrg.setText("Laporan Barang");
        mnlapbrg.addActionListener(this::mnlapbrgActionPerformed);
        jMenu3.add(mnlapbrg);

        mnlapuser.setText("Laporan User");
        jMenu3.add(mnlapuser);

        mnlaporder.setText("Laporan Tranksaksi");
        mnlaporder.addActionListener(this::mnlaporderActionPerformed);
        jMenu3.add(mnlaporder);

        mnLapBrgMsk.setText("Laporan Barang Masuk");
        mnLapBrgMsk.addActionListener(this::mnLapBrgMskActionPerformed);
        jMenu3.add(mnLapBrgMsk);

        mnLapBrgKlr.setText("Laporan Barang Keluar");
        mnLapBrgKlr.addActionListener(this::mnLapBrgKlrActionPerformed);
        jMenu3.add(mnLapBrgKlr);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Data");

        jdata_barang.setText("Data Barang ");
        jdata_barang.addActionListener(this::jdata_barangActionPerformed);
        jMenu4.add(jdata_barang);

        jstok_min.setText("Stok Barang Minimal");
        jstok_min.addActionListener(this::jstok_minActionPerformed);
        jMenu4.add(jstok_min);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlogoutActionPerformed
        this.dispose();         
        Form_Login login = new Form_Login();         
        login.setLocationRelativeTo(null);         
        login.setVisible(true); 
    }//GEN-LAST:event_mnlogoutActionPerformed

    private void mnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnbarangActionPerformed
          Form_Master_Barang barang = new Form_Master_Barang();         
          barang.setLocationRelativeTo(null);         
          barang.setVisible(true); 
    }//GEN-LAST:event_mnbarangActionPerformed

    private void jbarang_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarang_masukActionPerformed
        Form_Penerimaan_Barang msk = new Form_Penerimaan_Barang();
        msk.setLocationRelativeTo(null);
        msk.setIDUser(Ikode.getText()); // Menggunakan method setter
        msk.setVisible(true);
    }//GEN-LAST:event_jbarang_masukActionPerformed

    private void jstok_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstok_minActionPerformed
        Form_Stok_Barang_MinimalPM stokMin = new Form_Stok_Barang_MinimalPM(this, true);
        stokMin.setLocationRelativeTo(null);
        stokMin.setVisible(true);
    }//GEN-LAST:event_jstok_minActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           Inama.setText(NamaUser);
           Ikode.setText(kode);         
           Ilevel.setText(Level);         
           //getfoto();
    }//GEN-LAST:event_formWindowActivated

    private void mngantipasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngantipasswordActionPerformed
          Form_Ganti_Password gantipass = new Form_Ganti_Password();         
          gantipass.setLocationRelativeTo(null);         
          gantipass.setVisible(true);          
          gantipass.Kode_User=Ikode.getText(); 
    }//GEN-LAST:event_mngantipasswordActionPerformed

    private void mnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkeluarActionPerformed
         System.exit(0); 
    }//GEN-LAST:event_mnkeluarActionPerformed

    private void mnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuserActionPerformed
           Form_Master_User user = new Form_Master_User();         
           user.setLocationRelativeTo(null);         
           user.setVisible(true); 
    }//GEN-LAST:event_mnuserActionPerformed

    private void mnkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnkategoriActionPerformed
         try {
            Form_Master_Kategori Kategori = new Form_Master_Kategori();         
            Kategori.setLocationRelativeTo(null);         
            Kategori.setVisible(true); 
            Kategori.toFront(); // Memastikan form muncul di paling depan
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka Form Kategori: " + e.getMessage());
        }
    }//GEN-LAST:event_mnkategoriActionPerformed

    private void mnlapbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlapbrgActionPerformed
         try {
        // Ambil file .jrxml dari lokasi fisik project Maven
        File file = new File("src/main/java/gudang/Laporan_Barang.jrxml");
        
        if (!file.exists()) {
            JOptionPane.showMessageDialog(null, "File tidak ditemukan di: " + file.getAbsolutePath());
            return;
        }

        // Kompilasi file .jrxml menjadi JasperReport
        JasperReport jasperReport = JasperCompileManager.compileReport(file.getAbsolutePath());
        
        // Isi laporan dengan data dari database
        HashMap<String, Object> parameter = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(jasperReport, parameter, kon.setkoneksi());
        
        // Tampilkan viewer
        JasperViewer.viewReport(print, false);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error Kompilasi: " + e.getLocalizedMessage());
    }
    }//GEN-LAST:event_mnlapbrgActionPerformed

    private void mnLapBrgMskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapBrgMskActionPerformed
         Form_Laporan_PenerimaanPeriode Laporan_Msk = new Form_Laporan_PenerimaanPeriode();        
         Laporan_Msk.setLocationRelativeTo(null);          
         Laporan_Msk.setVisible(true);                     
        
    }//GEN-LAST:event_mnLapBrgMskActionPerformed

    private void mnLapBrgKlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapBrgKlrActionPerformed
        Form_Laporan_PengeluaranPeriode Laporan_Klr = new Form_Laporan_PengeluaranPeriode();        
        Laporan_Klr.setLocationRelativeTo(null);       
        Laporan_Klr.setVisible(true); 
    }//GEN-LAST:event_mnLapBrgKlrActionPerformed

    private void jbarang_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarang_keluarActionPerformed
       Form_Pengeluaran_Barang klr = new Form_Pengeluaran_Barang();
        klr.setLocationRelativeTo(null); // Diperbaiki dari setLocationRealativeTo
        klr.setIDUser(Ikode.getText());  // Mengirim ID User login
        klr.setVisible(true);
    }//GEN-LAST:event_jbarang_keluarActionPerformed

    private void jdata_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdata_barangActionPerformed
        Form_Data_Barang klr = new Form_Data_Barang();
        klr.setLocationRelativeTo(null); // Diperbaiki dari setLocationRealativeTo
        klr.setVisible(true);
    }//GEN-LAST:event_jdata_barangActionPerformed

    private void jOrderInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrderInventoryActionPerformed
        Form_Transaksi_Inventory formOrder = new Form_Transaksi_Inventory();
        formOrder.setVisible(true);
        formOrder.setIDUser(Ikode.getText());
        formOrder.setLocationRelativeTo(null);
    }//GEN-LAST:event_jOrderInventoryActionPerformed

    private void mnlaporderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnlaporderActionPerformed
        Form_Laporan_TransaksiPeriode Laporan_Klr = new Form_Laporan_TransaksiPeriode();        
        Laporan_Klr.setLocationRelativeTo(null);
        Laporan_Klr.setVisible(true);
    }//GEN-LAST:event_mnlaporderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_MenuUtamaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ikode;
    private javax.swing.JLabel Ilevel;
    private javax.swing.JLabel Inama;
    private javax.swing.JLabel clock;
    private javax.swing.JLabel date;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jOrderInventory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem jbarang_keluar;
    private javax.swing.JMenuItem jbarang_masuk;
    private javax.swing.JMenuItem jdata_barang;
    private javax.swing.JMenuItem jstok_min;
    private javax.swing.JMenuItem mnLapBrgKlr;
    private javax.swing.JMenuItem mnLapBrgMsk;
    private javax.swing.JMenuItem mnbarang;
    private javax.swing.JMenuItem mngantipassword;
    private javax.swing.JMenuItem mnkategori;
    private javax.swing.JMenuItem mnkeluar;
    private javax.swing.JMenuItem mnlapbrg;
    private javax.swing.JMenuItem mnlaporder;
    private javax.swing.JMenuItem mnlapuser;
    private javax.swing.JMenuItem mnlogout;
    private javax.swing.JMenuItem mnuser;
    private javax.swing.JMenu nmTranksaksi;
    // End of variables declaration//GEN-END:variables
}
