/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang;

import com.mycompany.gudang.koneksi;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PagarKun
 */
public class Form_Data_Barang extends javax.swing.JFrame {
    
     koneksi kon = new koneksi();
        private Object[][] databarang = null;
        private String[] label = {
          "KODE BARANG",
          "NAMA KATEGORI",
          "NAMA BARANG",
          "STOK",
          "MIN.STOK"
        };
        

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Data_Barang.class.getName());

    /**
     * Creates new form Form_Data_Barang
     */
    
    
    public Form_Data_Barang() {
    initComponents();
    kon.setkoneksi();
    BacaTabelBarang();
}
    
     private void BacaTabelBarang() {
        try {
          String sql = "Select *From tb_barang order by kd_brg";
          kon.rs = kon.st.executeQuery(sql);
          ResultSetMetaData m = kon.rs.getMetaData();
          int kolom = m.getColumnCount();
          int baris = 0;
          while (kon.rs.next()) {
            baris = kon.rs.getRow();
          }
          databarang = new Object[baris][kolom];
          int x = 0;
          kon.rs.beforeFirst();
          while (kon.rs.next()) {
            databarang[x][0] = kon.rs.getString("kd_brg");
            databarang[x][1] = kon.rs.getString("nm_kategori");
            databarang[x][2] = kon.rs.getString("nm_brg");
            databarang[x][3] = kon.rs.getString("stok");
            databarang[x][4] = kon.rs.getString("min_stok");
            x++;
          }
          tbl_barang.setModel(new DefaultTableModel(databarang, label));
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }
      }
     
     
     private void CariTabelBarang() {
        try {
          String sql = "select *from tb_barang where kd_brg like '%" + tcari.getText() + "%'" + "or nm_kategori like '%" + tcari.getText() + "%'" + "or nm_brg like '%" + tcari.getText() + "%'";
          kon.rs = kon.st.executeQuery(sql);
          ResultSetMetaData m = kon.rs.getMetaData();
          int kolom = m.getColumnCount();
          int baris = 0;
          while (kon.rs.next()) {
            baris = kon.rs.getRow();
          }
          databarang = new Object[baris][kolom];
          int x = 0;
          kon.rs.beforeFirst();
          while (kon.rs.next()) {
            databarang[x][0] = kon.rs.getString("kd_brg");
            databarang[x][1] = kon.rs.getString("nm_kategori");
            databarang[x][2] = kon.rs.getString("nm_brg");
            databarang[x][3] = kon.rs.getString("stok");
            databarang[x][4] = kon.rs.getString("min_stok");
            x++;
          }
          tbl_barang.setModel(new DefaultTableModel(databarang, label));
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }
      }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tbl_barang.setBackground(new java.awt.Color(204, 204, 204));
        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_barang);

        tcari.setBackground(new java.awt.Color(153, 153, 153));
        tcari.addActionListener(this::tcariActionPerformed);
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcariKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cari Barang");
        jLabel1.setMaximumSize(new java.awt.Dimension(75, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void tcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyTyped
       CariTabelBarang(); 
    }//GEN-LAST:event_tcariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Data_Barang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
